### ISSUE TITLE
Test count reads instructions

### ISSUE THREAD

**Issue by deflaux** [googlegenomics/start-here#31]
And update public data as needed.  The first command line on http://googlegenomics.readthedocs.org/en/staging/use_cases/analyze_reads/count_reads.html

Yields error:
```
Error: gs://genomics-public-data/platinum-genomes/bam/NA12877_S1.bam.bai not found.
```

**Comment by pgrosu** [comment]
Hi Nicole,

It's not as bad as you might think.  Probably adding the following parameter might fix this:

```
--shardBAMReading=false
```

Otherwise generating the `bai` index files is fairly straightforward via the following:

```
samtools index NA12877_S1.bam 
```

Hope it helps,
~p

**Comment by deflaux** [comment]
*bai files are now in gs://genomics-public-data/platinum-genomes/bam/

**Comment by pgrosu** [comment]
Sweeeeeet! :)

Thanks Nicole,
~p

**Comment by deflaux** [comment]
This is complete and also several corresponding [integration tests](https://github.com/googlegenomics/dataflow-java/blob/master/src/test/java/com/google/cloud/genomics/dataflow/pipelines/CountReadsITCase.java) have been added.
