### ISSUE TITLE
Document SAMRecord flag-setting

### ISSUE THREAD

**Issue by melissachang** [googlegenomics/start-here#36]
https://github.com/googlegenomics/gatk-tools-java/blob/e0375190427bb44057691b4461c0a91f0761e6d8/src/main/java/com/google/cloud/genomics/gatk/common/GenomicsConverter.java has

// Set flags, as advised in http://google-genomics.readthedocs.org/en/latest/migrating_tips.html

That url no longer exists. It was deleted in https://github.com/googlegenomics/start-here/pull/7/files

It would be useful to have that documentation somewhere, outside the context of v1beta -> v1beta2 migration.

**Comment by deflaux** [comment]
I restored it with [this commit](https://github.com/googlegenomics/start-here/commit/af1ae7a40b522893b2a992be102f4ff72d45a54d) but did not add it to the TOC.  @melissachang do you want to make any changes to it before I push it to live?

http://google-genomics.readthedocs.org/en/staging/migrating_tips.html

**Comment by melissachang** [comment]
I don't think we should restore
http://google-genomics.readthedocs.org/en/staging/migrating_tips.html since
v1beta doesn't exist anymore.

It seems like the flags pseudocode in migrating_tips.html is useful, even
though we don't have v1beta anymore. Maybe add a section to
http://google-genomics.readthedocs.org/en/staging/use_cases/run_picard_and_gatk/index.html?highlight=picard
?

Whereever you end up putting it, please also update the url in
https://github.com/googlegenomics/gatk-tools-java/blob/e0375190427bb44057691b4461c0a91f0761e6d8/src/main/java/com/google/cloud/genomics/gatk/common/GenomicsConverter.java#L158

**Comment by deflaux** [comment]
Okay, I will proceed with restoring it (its unlinked so it won't be too much clutter) and I added issue https://github.com/googlegenomics/gatk-tools-java/issues/15 for the real fix.  Thanks @melissachang !
